# GENERAL SETTINS

cluster.name:    "eren"
node.name:       "eren-node-1"
node.attr.zone:  "zone1"

#node.roles: [ "master", "data" ]
#discovery.zen.minimum_master_nodes: 1

network.host: 0.0.0.0

http.port: 9200
transport.port: 9300

script.allowed_types: inline

path.repo: ["/usr/share/elasticsearch"]
xpack.license.self_generated.type: trial
xpack.security.enabled: false
